on:
  push:

jobs:
  docker:
    uses: guillaumedsde/qbittorrent-distroless/.github/workflows/docker.yml@master
    with:
      # FIXME: retrieve this automatically
      software-version: "1.12"
      platforms: |
        linux/amd64
    secrets: inherit