on:
  push:

jobs:
  docker:
    uses: ./.github/workflows/docker.yml
    with:
      # FIXME: retrieve this automatically
      software-version: "1.13"
      platforms: |
        linux/amd64
    secrets: inherit